images: data/images/group-3
conf: 0.5
imgsz: 720
project: runs/detect

models:
  - name: egat
    weights: models/egat.pt
  - name: ppe-stecon-0
    weights: models/stecon-0.pt
  - name: ppe-stecon-01
    weights: models/stecon-01.pt
  - name: ppe-stecon-1
    weights: models/stecon-1.pt
