dataset: data/dataset/ppe_stecon_training_v1/ppe_stecon_training_v1.yaml
split: val
imgsz: 720
batch: 16
conf: 0.5
iou: 0.5
project: runs/val

models:
  - name: egat
    weights: models/egat.pt
  - name: ppe-stecon-0
    weights: models/stecon-0.pt
  - name: ppe-stecon-01
    weights: models/stecon-01.pt
  - name: ppe-stecon-1
    weights: models/stecon-1.pt
