model:    models/raw_weight/yolo11n.pt
data:     data/dataset/physical_fight/physical_fight.yaml
epochs:   1000
imgsz:    720
batch:    16
freeze:   10
lr0:      0.001
patience: 100
project:  runs/train
name:     physical_fight
