model:   runs/train/ppe-stecon/weights/best.pt
data:    data/dataset/ppe_stecon_training/ppe_stecon_training.yaml
split:   val
imgsz:   720
batch:   16
conf:    0.5
iou:     0.5
project: runs/val
name:    ppe-stecon
